[tool.poetry]
name = "HIN"
version = "1.0.0"
description = "Interview"
authors = ["HIN"]

readme = 'README.md'

[tool.poetry.dependencies]
python = "3.8"
numpy = "*"
PySide2 = "*"
pyqtgraph = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

